### ISSUE TITLE
Tests are broken, as they rely on outdated giantswarm/mock-api image/repo

### ISSUE THREAD

**Issue by marians** [giantswarm/giantswarm-js-client#45]
We should be able to test the client in CircleCI.

Can we mock the responses? There are several modules available, e. g.:

https://github.com/M6Web/superagent-mock

**Comment by oponder** [comment]
Yeah, I actually went down that road before already. But when I redid things I decided to drop the mocking and talk to a real (but mocked) server. This is because the superagent-mock was always returning just slightly different things than a real request would return (I even did various PR's to superagent-mock)

I'm not sure anymore what caused me to drop superagent-mock though, it might have been some functionality like websockets, or problems with testing the promise returns.

Regardless, I think we could also freshen up `mock-api` and run the tests on CircleCI by starting a `mock-api` docker instance right?

**Comment by marians** [comment]
> Regardless, I think we could also freshen up mock-api and run the tests on CircleCI by starting a mock-api docker instance right?

Right

**Comment by marians** [comment]
If this client is supposed to rely on https://github.com/giantswarm/mock-api, then that one should be public, too. Same for the according image on Quay.io.

**Comment by oponder** [comment]
I'm ok with that.

**Comment by marians** [comment]
The new generated client has generated tests. Closing.
